<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_TOKEN' => 'Token di sicurezza',
    'ATTR_CREATED' => 'Creato il',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_NAME' => 'Nome',
    'ATTR_NEW_EMAIL' => 'Nuova e-mail',
    'ATTR_NEW_PASSWORD' => 'Nuova password',
    'ATTR_NEW_REPASSWORD' => 'Ripeti nuova password',
    'ATTR_OLDEMAIL' => 'Attuale e-mail',
    'ATTR_OLDPASSWORD' => 'Attuale password',
    'ATTR_PASSWORD' => 'Password',
    'ATTR_REMEMBER_ME' => 'Ricordami',
    'ATTR_REPASSWORD' => 'Ripeti password',
    'ATTR_ROLE' => 'Ruolo',
    'ATTR_STATUS' => 'Stato',
    'ATTR_SURNAME' => 'Cognome',
    'ATTR_UPDATED' => 'Aggiornato il',
    'ATTR_USERNAME' => 'Username',
    'BACKEND_CREATE_SUBMIT' => 'Salva',
    'BACKEND_CREATE_SUBTITLE' => 'Creazione Utente',
    'BACKEND_CREATE_TITLE' => 'Utenti',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'L\'Utente non è stato salvato. Riprova!',
    'BACKEND_INDEX_SUBTITLE' => 'Lista Utenti',
    'BACKEND_INDEX_TITLE' => 'Utenti',
    'BACKEND_LOGIN_RECOVERY' => 'Recupera password',
    'BACKEND_LOGIN_SUBMIT' => 'Accedi',
    'BACKEND_LOGIN_TITLE' => 'Accedi',
    'BACKEND_PROMPT_ROLE' => 'Seleziona Ruolo',
    'BACKEND_PROMPT_STATUS' => 'Seleziona Stato',
    'BACKEND_UPDATE_SUBMIT' => 'Modifica',
    'BACKEND_UPDATE_SUBTITLE' => 'Aggiornamento utente',
    'BACKEND_UPDATE_TITLE' => 'Utenti',
    'EMAIL_SUBJECT_CHANGE' => 'Token di conferma Email',
    'EMAIL_SUBJECT_RECOVERY' => 'La tua richiesta di reset della password',
    'EMAIL_SUBJECT_SIGNUP' => 'Token di conferma Email',
    'ERROR_MSG_INVALID_OLD_PASSWORD' => 'Password attuale non valida',
    'ERROR_MSG_INVALID_USERNAME_OR_PASSWORD' => 'Username o Password errati',
    'FRONTEND_EMAIL_CHANGE_SUBMIT' => 'Cambia',
    'FRONTEND_EMAIL_CHANGE_TITLE' => 'Cambia indirizzo e-mail',
    'FRONTEND_FLASH_FAIL_ACTIVATION' => 'L\'Utente non è stato attivato. Riprova!',
    'FRONTEND_FLASH_FAIL_EMAIL_CHANGE' => 'L\'Email non è stata modificata. Riprova!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION' => 'L\'Email non è stata confermata. Riprova!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION_WITH_INVALID_KEY' => 'Token di richiesta non valido.',
    'FRONTEND_FLASH_FAIL_PASSWORD_CHANGE' => 'La password non è stata modificata. Riprova!',
    'FRONTEND_FLASH_FAIL_RECOVERY' => 'Il recupero della Password non è riuscito. Riprova!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION' => 'Il recupero della Password non è riuscito. Riprova!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION_WITH_INVALID_KEY' => 'Token di richiesta non valido.',
    'FRONTEND_FLASH_FAIL_RESEND' => 'Reinvio della email di conferma non riuscito. Riprova!',
    'FRONTEND_FLASH_FAIL_SIGNUP' => 'registrazione utente non riuscita. Riprova!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Aggiornamento del Profilo non riuscito. Riprova!',
    'FRONTEND_FLASH_SUCCESS_ACTIVATION' => 'Il tuo account è stato attivato correttamente. Adesso è possibile accedere utilizzando il nome utente e la password che hai scelto al momento della registrazione.',
    'FRONTEND_FLASH_SUCCESS_NEW_EMAIL_CONFIRMATION' => 'La tua email è stata confermata con successo.',
    'FRONTEND_FLASH_SUCCESS_PASSWORD_CHANGE' => 'La tua password è stata modificata con successo.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY' => 'Una e-mail con un link di verifica è stata inviata all\'indirizzo e-mail da te inserito.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY_CONFIRMATION' => 'Reset della password avvenuto con successo. Adesso è possibile effettuare il login al sito.',
    'FRONTEND_FLASH_SUCCESS_RESEND' => 'Una e-mail con un link di verifica è stata inviata all\'indirizzo e-mail da te inserito.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITHOUT_LOGIN' => 'Il tuo account è stato creato ed una e-mail con un link di verifica è stata inviata all\'indirizzo e-mail da te inserito.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITH_LOGIN' => 'Il tuo account è stato creato.',
    'FRONTEND_FLASH_SUCCES_EMAIL_CHANGE' => 'Il tuo indirizzo email è stato modificato con successo.',
    'FRONTEND_FLASH_SUCCES_UPDATE' => 'Il tuo account è stato aggiornato con successo.',
    'FRONTEND_INDEX_SUBTITLE' => 'Lista Utenti',
    'FRONTEND_INDEX_TITLE' => 'Utenti',
    'FRONTEND_LOGIN_OR' => 'o',
    'FRONTEND_LOGIN_RECOVERY' => 'Recupera password',
    'FRONTEND_LOGIN_SUBMIT' => 'Accedi',
    'FRONTEND_LOGIN_TITLE' => 'Accedi',
    'FRONTEND_PASSWORD_CHANGE_SUBMIT' => 'Modifica',
    'FRONTEND_PASSWORD_CHANGE_TITLE' => 'Modifica password',
    'FRONTEND_RECOVERY_CONFIRMATION_SUBMIT' => 'Salva',
    'FRONTEND_RECOVERY_CONFIRMATION_TITLE' => 'Recupero Password',
    'FRONTEND_RECOVERY_SUBMIT' => 'Recupera',
    'FRONTEND_RECOVERY_TITLE' => 'Recupera password',
    'FRONTEND_RESEND_SUBMIT' => 'Reinvia',
    'FRONTEND_RESEND_TITLE' => 'Reinvio e-mail di conferma',
    'FRONTEND_SETTINGS_LABEL' => 'Impostazioni',
    'FRONTEND_SIGNUP_RESEND' => 'Reinvia e-mail di conferma',
    'FRONTEND_SIGNUP_SUBMIT' => 'Registrati',
    'FRONTEND_SIGNUP_TITLE' => 'Registrati',
    'FRONTEND_UPDATE_SUBMIT' => 'Modifica',
    'FRONTEND_UPDATE_TITLE' => 'Modifica profilo utente',
    'STATUS_ACTIVE' => 'Attivo',
    'STATUS_BANNED' => 'Bannato',
    'STATUS_INACTIVE' => 'Inattivo',
];
