<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_TOKEN' => 'Sicherheitsmerkmal',
    'ATTR_CREATED' => 'Erzeugt am',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_NAME' => 'Name',
    'ATTR_NEW_EMAIL' => 'Neue e-mail',
    'ATTR_NEW_PASSWORD' => 'Neues Passwort',
    'ATTR_NEW_REPASSWORD' => 'Wiederhole neues Passwort',
    'ATTR_OLDEMAIL' => 'Aktuelle e-mail',
    'ATTR_OLDPASSWORD' => 'Aktuelles Passwort',
    'ATTR_PASSWORD' => 'Passwort',
    'ATTR_REMEMBER_ME' => 'An mich erinnern',
    'ATTR_REPASSWORD' => 'Wiederhole Passwort',
    'ATTR_ROLE' => 'Rolle',
    'ATTR_STATUS' => 'Status',
    'ATTR_SURNAME' => 'Familienname',
    'ATTR_UPDATED' => 'Geändert am',
    'ATTR_USERNAME' => 'Benutzername',
    'BACKEND_CREATE_SUBMIT' => 'Speichern',
    'BACKEND_CREATE_SUBTITLE' => 'Benutzer erzeugen',
    'BACKEND_CREATE_TITLE' => 'Benutzer',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Benutzer wurde nicht gespeichert. Bitte neuerlich versuchen!',
    'BACKEND_INDEX_SUBTITLE' => 'Benutzerliste',
    'BACKEND_INDEX_TITLE' => 'Benutzer',
    'BACKEND_LOGIN_RECOVERY' => 'Passwort wiederherstellen',
    'BACKEND_LOGIN_SUBMIT' => 'Anmelden',
    'BACKEND_LOGIN_TITLE' => 'Anmelden',
    'BACKEND_PROMPT_ROLE' => 'Wähle Rolle',
    'BACKEND_PROMPT_STATUS' => 'Wähle Status',
    'BACKEND_UPDATE_SUBMIT' => 'Ändern',
    'BACKEND_UPDATE_SUBTITLE' => 'Benutzer ändern',
    'BACKEND_UPDATE_TITLE' => 'Benutzer',
    'EMAIL_SUBJECT_CHANGE' => 'Email Bestätigungsmerkmal',
    'EMAIL_SUBJECT_RECOVERY' => 'Ihre Passwort Rücksetz-Anforderung',
    'EMAIL_SUBJECT_SIGNUP' => 'Email Bestätigungsmerkmal',
    'ERROR_MSG_INVALID_OLD_PASSWORD' => 'Ungültiges aktuelles Passwort',
    'ERROR_MSG_INVALID_USERNAME_OR_PASSWORD' => 'Benutzername oder Passwort ungültig',
    'FRONTEND_EMAIL_CHANGE_SUBMIT' => 'Ändern',
    'FRONTEND_EMAIL_CHANGE_TITLE' => 'Ändere e-mail Adresse',
    'FRONTEND_FLASH_FAIL_ACTIVATION' => 'Benutzer noch nicht aktiviert. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_FAIL_EMAIL_CHANGE' => 'Email wurde nicht geändert. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION' => 'Email noch nicht bestätigt. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION_WITH_INVALID_KEY' => 'Ungültiges Anforderungsmerkmal.',
    'FRONTEND_FLASH_FAIL_PASSWORD_CHANGE' => 'Passwort nicht geändert. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_FAIL_RECOVERY' => 'Passwort-Rückgewinnung fehlerhaft. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION' => 'Passwort-Rückgewinnung fehlerhaft. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION_WITH_INVALID_KEY' => 'Ungültiges Anforderungsmerkmal.',
    'FRONTEND_FLASH_FAIL_RESEND' => 'E-mail Bestätigung fehlerhaft. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_FAIL_SIGNUP' => 'Anmeldung fehlerhaft. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Profil-Änderung fehlerhaft. Bitte neuerlich versuchen!',
    'FRONTEND_FLASH_SUCCESS_ACTIVATION' => 'Ihr Account wurde erfolgreich aktiviert. Sie können sich nun anmelden mit Benutzerkennung und Passwort, die Sie bei der Registrierung gewählt haben.',
    'FRONTEND_FLASH_SUCCESS_NEW_EMAIL_CONFIRMATION' => 'Ihre email wurde erfolgreich bestätigt.',
    'FRONTEND_FLASH_SUCCESS_PASSWORD_CHANGE' => 'Ihr Passwort wurde erfolgreich geändert.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY' => 'Ein Bestätigungs-link wurde an die von Ihnen angegebene email-Adresse gesendet.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY_CONFIRMATION' => 'Reset Ihres Passworts war erfolgreich. Sie können sich nun anmelden.',
    'FRONTEND_FLASH_SUCCESS_RESEND' => 'Ein Bestätigungs-link wurde an die von Ihnen angegebene email-Adresse gesendet.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITHOUT_LOGIN' => 'Ihr Account wurde angelegt and ein Bestätigungs-link wurde an die von Ihnen angegebene email-Adresse gesendet.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITH_LOGIN' => 'Ihr Account wurde angelegt.',
    'FRONTEND_FLASH_SUCCES_EMAIL_CHANGE' => 'Ihre email Adresse wurde erfolgreich geändert.',
    'FRONTEND_FLASH_SUCCES_UPDATE' => 'Ihr Account wurde erfolgreich geändert.',
    'FRONTEND_INDEX_SUBTITLE' => 'Benutzerliste',
    'FRONTEND_INDEX_TITLE' => 'Benutzer',
    'FRONTEND_LOGIN_OR' => 'oder',
    'FRONTEND_LOGIN_RECOVERY' => 'Passwort wiederherstellen',
    'FRONTEND_LOGIN_SUBMIT' => 'Anmelden',
    'FRONTEND_LOGIN_TITLE' => 'Anmelden',
    'FRONTEND_PASSWORD_CHANGE_SUBMIT' => 'Ändern',
    'FRONTEND_PASSWORD_CHANGE_TITLE' => 'Ändere Passwort',
    'FRONTEND_RECOVERY_CONFIRMATION_SUBMIT' => 'Speichern',
    'FRONTEND_RECOVERY_CONFIRMATION_TITLE' => 'Passwort wiederherstellen',
    'FRONTEND_RECOVERY_SUBMIT' => 'Wiederherstellen',
    'FRONTEND_RECOVERY_TITLE' => 'Passwort wiederherstellen',
    'FRONTEND_RESEND_SUBMIT' => 'Nochmals senden',
    'FRONTEND_RESEND_TITLE' => 'E-mail Bestätigung nochmals senden',
    'FRONTEND_SETTINGS_LABEL' => 'Einstellungen',
    'FRONTEND_SIGNUP_RESEND' => 'E-mail Bestätigung nochmals senden',
    'FRONTEND_SIGNUP_SUBMIT' => 'Registrieren',
    'FRONTEND_SIGNUP_TITLE' => 'Registrierung',
    'FRONTEND_UPDATE_SUBMIT' => 'Ändern',
    'FRONTEND_UPDATE_TITLE' => 'Benutzerprofil Ändern',
    'STATUS_ACTIVE' => 'Aktiv',
    'STATUS_BANNED' => 'Verbannt',
    'STATUS_INACTIVE' => 'Inaktiv',
];
