<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_TOKEN' => 'Token de segurança',
    'ATTR_CREATED' => 'Criado em',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_NAME' => 'Nome',
    'ATTR_NEW_EMAIL' => 'Novo e-mail',
    'ATTR_NEW_PASSWORD' => 'Nova senha',
    'ATTR_NEW_REPASSWORD' => 'Repetir nova senha',
    'ATTR_OLDEMAIL' => 'E-mail atual',
    'ATTR_OLDPASSWORD' => 'Senha atual',
    'ATTR_PASSWORD' => 'Senha',
    'ATTR_REMEMBER_ME' => 'Lembrar dados',
    'ATTR_REPASSWORD' => 'Repetir senha',
    'ATTR_ROLE' => 'Função',
    'ATTR_STATUS' => 'Status',
    'ATTR_SURNAME' => 'Sobrenome',
    'ATTR_UPDATED' => 'Atualizado em',
    'ATTR_USERNAME' => 'Usuário',
    'BACKEND_CREATE_SUBMIT' => 'Salvar',
    'BACKEND_CREATE_SUBTITLE' => 'Criando usuário',
    'BACKEND_CREATE_TITLE' => 'Usuário',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'Usuário não foi salvo. Por favor tente novamente!',
    'BACKEND_INDEX_SUBTITLE' => 'Lista de usuários',
    'BACKEND_INDEX_TITLE' => 'Usuários',
    'BACKEND_LOGIN_RECOVERY' => 'Recuperar senha',
    'BACKEND_LOGIN_SUBMIT' => 'Entrar',
    'BACKEND_LOGIN_TITLE' => 'Entrar',
    'BACKEND_PROMPT_ROLE' => 'Selecionar função',
    'BACKEND_PROMPT_STATUS' => 'Selecionar status',
    'BACKEND_UPDATE_SUBMIT' => 'Atualizar',
    'BACKEND_UPDATE_SUBTITLE' => 'Atualizando usuário',
    'BACKEND_UPDATE_TITLE' => 'Usuários',
    'EMAIL_SUBJECT_CHANGE' => 'Email de confirmação',
    'EMAIL_SUBJECT_RECOVERY' => 'Seu pedido de redefinição de senha',
    'EMAIL_SUBJECT_SIGNUP' => 'Cadastro - Token de confirmação',
    'ERROR_MSG_INVALID_OLD_PASSWORD' => 'Senha atual inválida',
    'ERROR_MSG_INVALID_USERNAME_OR_PASSWORD' => 'Nome de usuário ou senha inválida',
    'FRONTEND_EMAIL_CHANGE_SUBMIT' => 'Alterar',
    'FRONTEND_EMAIL_CHANGE_TITLE' => 'Alterar endereço de e-mail',
    'FRONTEND_FLASH_FAIL_ACTIVATION' => 'Usuário não foi ativado. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_EMAIL_CHANGE' => 'Email não foi alterado. Porfavor tente novamente!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION' => 'E-mail não foi alterado. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_NEW_EMAIL_CONFIRMATION_WITH_INVALID_KEY' => 'Token inválido.',
    'FRONTEND_FLASH_FAIL_PASSWORD_CHANGE' => 'Senha não foi alterada. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_RECOVERY' => 'A senha não foi alterada. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION' => 'Recuperação de senha falhou. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_RECOVERY_CONFIRMATION_WITH_INVALID_KEY' => 'Token inválido.',
    'FRONTEND_FLASH_FAIL_RESEND' => 'Reenviar e-mail de confirmação falhou. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_SIGNUP' => 'Cadastro do usuário falhou. Por favor tente novamente!',
    'FRONTEND_FLASH_FAIL_UPDATE' => 'Atualização do perfil falhou. Por favor tente novamente!',
    'FRONTEND_FLASH_SUCCESS_ACTIVATION' => 'Sua conta foi ativada com sucesso. Agora você pode fazer login usando o nome de usuário e senha que você escolheu durante o registro.',
    'FRONTEND_FLASH_SUCCESS_NEW_EMAIL_CONFIRMATION' => 'Seu e-mail foi confirmado com sucesso.',
    'FRONTEND_FLASH_SUCCESS_PASSWORD_CHANGE' => 'Sua senha foi alterada com sucesso.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY' => 'Um link de confirmação foi enviado para o endereço de email que você informou.',
    'FRONTEND_FLASH_SUCCESS_RECOVERY_CONFIRMATION' => 'Senha reiniciada com sucesso. Agora você pode acessar o site.',
    'FRONTEND_FLASH_SUCCESS_RESEND' => 'Redefinição da senha realizada com sucesso. Agora você pode fazer login no site.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITHOUT_LOGIN' => 'Sua conta foi criada e um link de confirmação foi enviado para o endereço de email que você informou.',
    'FRONTEND_FLASH_SUCCESS_SIGNUP_WITH_LOGIN' => 'Seua conta foi criada.',
    'FRONTEND_FLASH_SUCCES_EMAIL_CHANGE' => 'O seu endereço de e-mail foi alterado com sucesso.',
    'FRONTEND_FLASH_SUCCES_UPDATE' => 'Sua conta foi atualizada com sucesso.',
    'FRONTEND_INDEX_SUBTITLE' => 'Lista de usuários',
    'FRONTEND_INDEX_TITLE' => 'Usuários',
    'FRONTEND_LOGIN_OR' => 'ou',
    'FRONTEND_LOGIN_RECOVERY' => 'Recuperar senha',
    'FRONTEND_LOGIN_SUBMIT' => 'Entrar',
    'FRONTEND_LOGIN_TITLE' => 'Entrar',
    'FRONTEND_PASSWORD_CHANGE_SUBMIT' => 'Alterar',
    'FRONTEND_PASSWORD_CHANGE_TITLE' => 'Alterar senha',
    'FRONTEND_RECOVERY_CONFIRMATION_SUBMIT' => 'Salvar',
    'FRONTEND_RECOVERY_CONFIRMATION_TITLE' => 'Recuperar senha',
    'FRONTEND_RECOVERY_SUBMIT' => 'Recuperar',
    'FRONTEND_RECOVERY_TITLE' => 'Recuperar senha',
    'FRONTEND_RESEND_SUBMIT' => 'Reenviar',
    'FRONTEND_RESEND_TITLE' => 'Reenviar email de confirmação',
    'FRONTEND_SETTINGS_LABEL' => 'Configurações',
    'FRONTEND_SIGNUP_RESEND' => 'Reenviar email de confirmação',
    'FRONTEND_SIGNUP_SUBMIT' => 'Entrar',
    'FRONTEND_SIGNUP_TITLE' => 'Entrar',
    'FRONTEND_UPDATE_SUBMIT' => 'Atualizar',
    'FRONTEND_UPDATE_TITLE' => 'Atualizar perfil do usuário',
    'STATUS_ACTIVE' => 'Ativo',
    'STATUS_BANNED' => 'Banido',
    'STATUS_INACTIVE' => 'Inativo',
];
